_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[[[0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]
           ...
           [0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]]

          [[0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]
           ...
           [0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]]

          [[0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]
           ...
           [0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]]

          [[0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]
           ...
           [0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]
           [0 0 0 ... 0 0 0]]]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x000001DAF9839F40>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 1000000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.8.18
        session_history: code\_session_history.ipynb
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 11
                - 49
                - 55
                - 105
            "3":
                - 2
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.8.18
            "5": 0.18.5
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
action_noise:
    value: None
action_space:
    value: Discrete(18)
algo:
    value: A2C
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object at 0x000001DAFA8DD0D0>
env_name:
    value: ALE/MarioBros-v5
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
export_path:
    value: ./exports/
gae_lambda:
    value: 1
gamma:
    value: 0.99
learning_rate:
    value: 0.0007
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x000001DAF98AF700>
max_grad_norm:
    value: 0.5
model_name:
    value: A2C_MarioBros
n_envs:
    value: 1
n_steps:
    value: 5
normalize_advantage:
    value: "False"
num_timesteps:
    value: 0
observation_space:
    value: Box(0, 255, (4, 84, 84), uint8)
policy:
    value: |-
        ActorCriticCnnPolicy(
          (features_extractor): NatureCNN(
            (cnn): Sequential(
              (0): Conv2d(4, 32, kernel_size=(8, 8), stride=(4, 4))
              (1): ReLU()
              (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
              (3): ReLU()
              (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
              (5): ReLU()
              (6): Flatten(start_dim=1, end_dim=-1)
            )
            (linear): Sequential(
              (0): Linear(in_features=3136, out_features=512, bias=True)
              (1): ReLU()
            )
          )
          (pi_features_extractor): NatureCNN(
            (cnn): Sequential(
              (0): Conv2d(4, 32, kernel_size=(8, 8), stride=(4, 4))
              (1): ReLU()
              (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
              (3): ReLU()
              (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
              (5): ReLU()
              (6): Flatten(start_dim=1, end_dim=-1)
            )
            (linear): Sequential(
              (0): Linear(in_features=3136, out_features=512, bias=True)
              (1): ReLU()
            )
          )
          (vf_features_extractor): NatureCNN(
            (cnn): Sequential(
              (0): Conv2d(4, 32, kernel_size=(8, 8), stride=(4, 4))
              (1): ReLU()
              (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
              (3): ReLU()
              (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
              (5): ReLU()
              (6): Flatten(start_dim=1, end_dim=-1)
            )
            (linear): Sequential(
              (0): Linear(in_features=3136, out_features=512, bias=True)
              (1): ReLU()
            )
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential()
            (value_net): Sequential()
          )
          (action_net): Linear(in_features=512, out_features=18, bias=True)
          (value_net): Linear(in_features=512, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticCnnPolicy'>
policy_kwargs:
    value: '{''optimizer_class'': <class ''torch.optim.rmsprop.RMSprop''>, ''optimizer_kwargs'': {''alpha'': 0.99, ''eps'': 1e-05, ''weight_decay'': 0}}'
policy_type:
    value: CnnPolicy
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x000001DAF98265E0>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1733352300487339700
tensorboard_log:
    value: runs/eabzxr8d
total_timesteps:
    value: 1000000
use_sde:
    value: "False"
verbose:
    value: 0
vf_coef:
    value: 0.5
videos_path:
    value: ./videos/
