_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.4
            "5": 0.18.5
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
eps_decay:
    value: 0.999985
eps_start:
    value: 1
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
